# Stage 1: Build the project
FROM maven:3.9.11-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Runtime image (lightweight)
FROM openjdk:17-jdk-slim
WORKDIR /app
ENV PORT=8081
EXPOSE 8081
COPY --from=build /app/target/Musify-*.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
