server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: "mongodb+srv://arnav:Arnav%402006@cluster0.fj8gi7o.mongodb.net/Musify?retryWrites=true&w=majority&appName=Cluster0"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "233188342295-drgmujf68ta1is994l8i8aaoed89sn3n.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - openid
              - profile
              - email

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

jwt:
  secret: "this_is_a_very_long_secure_secret_key_123456"
  expiration-ms: 86400000

file:
  upload-dir: uploads/

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
